In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/predbert/pred_bert.csv

In [3]:
df =pd.read_csv('/kaggle/input/predbert/pred_bert.csv')
df

,Unnamed: 0,Article,Reference Summary,Generated Summary
0,0,Fear shakes Mexico border city after violence ...,The attacks took place in several neighborhood...,Fear shakes Mexico border city after violence ...
1,1,Indian-origin boy finds millions of years old ...,"Siddak Singh Jhamat, known as Sid, was using a...",Indian-origin boy finds millions of years old ...
2,2,Representative ImageA 38-year-old Indian man h...,A 38-year-old Indian man has been charged with...,Representative ImageA 38-year-old Indian man h...
3,3,Residents get tested during their stay at a te...,"China on Apr 21 reported 2,119 locally transmi...",China coronavirus updates: Shanghai has extend...
4,4,Israeli PM Benjamin Netanyahu flew to Saudi Ar...,Israeli media reported Monday that Prime Minis...,Israeli PM Benjamin Netanyahu flew to Saudi Ar...
...,...,...,...,...
4482,4482,FILE - Tanks storing treated radioactive water...,A massive earthquake and tsunami in 2011 destr...,FILE - Tanks storing treated radioactive water...
4483,4483,Villagers clear debris caused by an earthquake...,"Over 680 tourists from France, Thailand, the N...",At least 16 people were killed and hundreds ot...
4484,4484,"Seif al-Islam, the son and one-time heir appar...","Seif al-Islam, the son and one-time heir appar...","Seif al-Islam, the son and one-time heir appar..."
4485,4485,Thai BoysMost members of the Thai youth footba...,Most members of the Thai youth football team r...,One of the boys will not join the ceremony as ...
4486,4486,Karachi to award citizens who identify people ...,The government of Pakistan's Sindh province ha...,Karachi to award citizens who identify people ...

In [4]:
!pip install rouge -q
!pip install evaluate -q
!pip install rouge-score -q

In [6]:
from rouge import Rouge
rouge = Rouge()
score = rouge.get_scores(df['Generated Summary'], df['Reference Summary'], avg = True)
RougeScore = pd.DataFrame(score).set_index([['recall','precision','f-measure']])
RougeScore

            rouge-1   rouge-2   rouge-l
recall     0.793772  0.704596  0.776727
precision  0.266530  0.189734  0.259389
f-measure  0.377978  0.280318  0.368517